### ISSUE TITLE
DO NOT DOWNLOAD IT MADE MY TOILET EXPLODE

### ISSUE THREAD

**Issue by NoviSadSucks** [itsthedot/browser-manager#1]
A WARNING FOR EVERYONE CONSIDERING TO DOWNLOAD THIS PROGRAM - IT WILL MAKE YOUR TOILET EXPLODE!!!!!

**Comment by itsthedot** [comment]
You have been reported for completely unreasonable behavior, Saturn. I suggest you piss off and stop harassing me.
